[phases.setup]
nixPkgs = ["python311", "gcc", "ffmpeg", "freetype", "fontconfig", "dejavu_fonts"]

[phases.install]
cmds = ["python3 -m pip install -r requirements.txt"]

[start]
cmd = "PYTHONPATH=. python3 creative_intelligence/webapp/app.py"
